on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          type: ${{ secrets.TYPE }}
          project_id: ${{ secrets.PROJECT_ID }}
          private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
          client_id: ${{ secrets.CLIENT_ID }}
          auth_uri: ${{ secrets.AUTH_URI }}
          token_uri: ${{ secrets.TOKEN_URI }}
          auth_provider_x509_cert_url: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
          client_x509_cert_url: ${{ secrets.CLIENT_X509_CERT_URL }}
          universe_domain: ${{ secrets.UNIVERSE_DOMAIN }}
